Filtered out compiler generated types that are currently being included with "IncludeUndocumentedItems"
Doraku/DefaultDocumentation pull request #83
Opened 2021-09-30 13:05 UTC by hairlesshobo

I have identified two issues with the current implementation of  the `IncudeUndocumentedItems` option.

### 1. The current output includes compiler generated "DisplayClass" types that should not be present.. see below:

```markdown
#### [TerminalUI](index.md 'index')
## FoxHollow.TerminalUI Namespace

| Classes | |
| :--- | :--- |
| [Helpers](FoxHollow_TerminalUI_Helpers.md 'FoxHollow.TerminalUI.Helpers') | Static class containing miscellaneous helper methods  |
| [Helpers.&lt;&gt;c__DisplayClass0_0](FoxHollow_TerminalUI_Helpers___c__DisplayClass0_0.md 'FoxHollow.TerminalUI.Helpers.&lt;&gt;c__DisplayClass0_0') |  |
| [Helpers.&lt;&gt;c__DisplayClass0_0.&lt;&lt;SetupTaskWatchdog&gt;b__0&gt;d](FoxHollow_TerminalUI_Helpers___c__DisplayClass0_0___SetupTaskWatchdog_b__0_d.md 'FoxHollow.TerminalUI.Helpers.&lt;&gt;c__DisplayClass0_0.&lt;&lt;SetupTaskWatchdog&gt;b__0&gt;d') |  |
| [KeyInput](FoxHollow_TerminalUI_KeyInput.md 'FoxHollow.TerminalUI.KeyInput') | Class used for reading key input from the terminal  |
| [Terminal](FoxHollow_TerminalUI_Terminal.md 'FoxHollow.TerminalUI.Terminal') | Static helper class for simplifying a console-based, interactive user interface  |
| [Terminal.&lt;&gt;c__DisplayClass72_0](FoxHollow_TerminalUI_Terminal___c__DisplayClass72_0.md 'FoxHollow.TerminalUI.Terminal.&lt;&gt;c__DisplayClass72_0') |  |
| [Terminal.&lt;&gt;c__DisplayClass72_0.&lt;&lt;Run&gt;b__0&gt;d](FoxHollow_TerminalUI_Terminal___c__DisplayClass72_0___Run_b__0_d.md 'FoxHollow.TerminalUI.Terminal.&lt;&gt;c__DisplayClass72_0.&lt;&lt;Run&gt;b__0&gt;d') |  |
| [TerminalColor](FoxHollow_TerminalUI_TerminalColor.md 'FoxHollow.TerminalUI.TerminalColor') | Allow to specify the default colors for the terminal  |
| [TerminalPoint](FoxHollow_TerminalUI_TerminalPoint.md 'FoxHollow.TerminalUI.TerminalPoint') | Class used to make interacting with terminal positioning much easier  |
| [TerminalPointMove](FoxHollow_TerminalUI_TerminalPointMove.md 'FoxHollow.TerminalUI.TerminalPointMove') | TerminalPoint helper class that allows to wrap a TerminalPoint move action into a using() { } block so that, upon exiting the  block, the cursor is automatically returned to the previous location  |
```

I was able to filter these out by adding a check in `DocItemReader` using `type.IsCompilerGeneratedOrIsInCompilerGeneratedClass()`. I compared the output with and without this check in place, and the only difference that is now being excluded is the invalid classes.

See below for output AFTER this check was put in place:

```markdown
#### [TerminalUI](index.md 'index')
## FoxHollow.TerminalUI Namespace

| Classes | |
| :--- | :--- |
| [Helpers](FoxHollow_TerminalUI_Helpers.md 'FoxHollow.TerminalUI.Helpers') | Static class containing miscellaneous helper methods<br/> |
| [KeyInput](FoxHollow_TerminalUI_KeyInput.md 'FoxHollow.TerminalUI.KeyInput') | Class used for reading key input from the terminal<br/> |
| [Terminal](FoxHollow_TerminalUI_Terminal.md 'FoxHollow.TerminalUI.Terminal') | Static helper class for simplifying a console-based, interactive user interface<br/> |
| [TerminalColor](FoxHollow_TerminalUI_TerminalColor.md 'FoxHollow.TerminalUI.TerminalColor') | Allow to specify the default colors for the terminal<br/> |
| [TerminalPoint](FoxHollow_TerminalUI_TerminalPoint.md 'FoxHollow.TerminalUI.TerminalPoint') | Class used to make interacting with terminal positioning much easier<br/> |
| [TerminalPointMove](FoxHollow_TerminalUI_TerminalPointMove.md 'FoxHollow.TerminalUI.TerminalPointMove') | TerminalPoint helper class that allows to wrap a TerminalPoint<br/>move action into a using() { } block so that, upon exiting the <br/>block, the cursor is automatically returned to the previous location<br/> |
```

### 2. The output generates a `.md` file and a `_Module.md` file, and an empty row in the `index.md` file. See below:

![image](https://user-images.githubusercontent.com/3877800/135459739-6d602c08-8555-485e-aa63-bd8442364c11.png)

I have attached `.md` and `_Module.md` in case you would like to review what is being generated

[.md](https://github.com/Doraku/DefaultDocumentation/files/7259674/default.md)
[_Module_.md](https://github.com/Doraku/DefaultDocumentation/files/7259677/_Module_.md)

Additionally.., this is what the `index.md` file looks:

```markdown
#### [TerminalUI](index.md 'index')

| Namespaces | |
| :--- | :--- |
| [](.md '') |  |
| [FoxHollow.TerminalUI](FoxHollow_TerminalUI.md 'FoxHollow.TerminalUI') |  |
| [FoxHollow.TerminalUI.Elements](FoxHollow_TerminalUI_Elements.md 'FoxHollow.TerminalUI.Elements') |  |
| [FoxHollow.TerminalUI.Types](FoxHollow_TerminalUI_Types.md 'FoxHollow.TerminalUI.Types') |  |
```

I was able to filter out this invalid namespace and type entry by looking for a type with no namespace defined in `DocItemReader`: 

```csharp
if (String.IsNullOrWhiteSpace(type.Namespace))
{
    _logger.Debug($"Skipping documentation for type \"{type.FullName}\": empty namespace");
    continue;
}
```

This pull request resolves both of these issues

2021-09-30 22:49 UTC, Doraku requested changes
Damn I thought I had taken care of the empty namespace and module type but I probably changed my arguments at one point when testing, thanks for bringing it up and even searching for a fix!
Just for completeness, I think the real missing `IsCompilerGenerated` check is line 105:
```csharp
                foreach (ITypeDefinition currentType in declaringTypes)
                {
                    if (!_items.TryGetValue(currentType.GetIdString(), out DocItem declaringTypeDocItem))
                    {
                        /// new check
                       if (currentType.IsCompilerGenerated())
                       {
                            _logger.Debug($"Skipping documentation for type \"{type.FullName}\": declaring type \"{declaringTypeDocItem.FullName}\" is compiler generated");
                            parentDocItem = null;
                            break;
                       }
                       /// 

                        declaringTypeDocItem = GetDocItem(currentType, parentDocItem);

                        if (declaringTypeDocItem.Documentation?.HasExclude() is true)
                        {
                            _logger.Debug($"Skipping documentation for type \"{type.FullName}\": exclude tag found in declaring type \"{declaringTypeDocItem.FullName}\" documentation");
                            parentDocItem = null;
                            break;
                        }

                        docItemsToAdd.Add(declaringTypeDocItem);
                    }

                    parentDocItem = declaringTypeDocItem;
                }
```
Can you check if this remove the extra types/members without the `IsCompilerGeneratedOrIsInCompilerGeneratedClass` call?
If not then you can probably replace the `IsCompilerGenerated` calls by `IsCompilerGeneratedOrIsInCompilerGeneratedClass` as this one probably include the former check instead of keeping both :)

2021-09-30 23:56 UTC, hairlesshobo commented
Sure, I will give this a shot in the morning and let you know what I find.

2021-10-01 18:35 UTC, hairlesshobo commented
OK, I made the requested change and confirmed that solution works as well.

2021-10-01 20:01 UTC, Doraku approved these changes

2021-10-01 20:02 UTC, merged

2021-10-01 20:02 UTC, Doraku commented
Thx again for those fixes :)